"""baseline

Revision ID: 4594cf56bba2
Revises: 
Create Date: 2026-08-10 03:07:52.020713
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '4594cf56bba2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform_problem_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('topic_tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_platform'), 'problem', ['platform'], unique=False)
    op.create_index(op.f('ix_problem_platform_problem_id'), 'problem', ['platform_problem_id'], unique=False)
    op.create_table('topic',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_name'), 'topic', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('agentlog',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('final_plan', sa.JSON(), nullable=True),
    sa.Column('reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calendar_context', sa.JSON(), nullable=True),
    sa.Column('deadline_context', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentlog_user_id'), 'agentlog', ['user_id'], unique=False)
    op.create_table('apikey',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikey_key'), 'apikey', ['key'], unique=True)
    op.create_index(op.f('ix_apikey_user_id'), 'apikey', ['user_id'], unique=False)
    op.create_table('calendarconnection',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendarconnection_user_id'), 'calendarconnection', ['user_id'], unique=False)
    op.create_table('knowledgenode',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fsrs_stability', sa.Float(), nullable=False),
    sa.Column('fsrs_difficulty', sa.Float(), nullable=False),
    sa.Column('last_review', sa.DateTime(), nullable=False),
    sa.Column('practice_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgenode_topic_id'), 'knowledgenode', ['topic_id'], unique=False)
    op.create_index(op.f('ix_knowledgenode_user_id'), 'knowledgenode', ['user_id'], unique=False)
    op.create_table('learningevent',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('mistakes', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learningevent_topic_id'), 'learningevent', ['topic_id'], unique=False)
    op.create_index(op.f('ix_learningevent_user_id'), 'learningevent', ['user_id'], unique=False)
    op.create_table('problemtopiclink',
    sa.Column('problem_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('problem_id', 'topic_id')
    )
    op.create_table('solveattempt',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('problem_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('first_keystroke_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('time_to_understand_s', sa.Integer(), nullable=True),
    sa.Column('time_to_write_s', sa.Integer(), nullable=True),
    sa.Column('num_submissions', sa.Integer(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence_weight', sa.Float(), nullable=False),
    sa.Column('recall_strength', sa.Float(), nullable=True),
    sa.Column('perceived_difficulty', sa.Float(), nullable=True),
    sa.Column('days_since_prev_review', sa.Float(), nullable=True),
    sa.Column('stability_at_review', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solveattempt_problem_id'), 'solveattempt', ['problem_id'], unique=False)
    op.create_index(op.f('ix_solveattempt_user_id'), 'solveattempt', ['user_id'], unique=False)
    op.create_table('syncsource',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('auth_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syncsource_user_id'), 'syncsource', ['user_id'], unique=False)
    op.create_table('topicprerequisitelink',
    sa.Column('topic_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prerequisite_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('topic_id', 'prerequisite_id')
    )
    op.create_table('usermemoryparams',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decay_exponent', sa.Float(), nullable=False),
    sa.Column('stability_growth', sa.Float(), nullable=False),
    sa.Column('speed_baselines', sa.JSON(), nullable=True),
    sa.Column('attempts_observed', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('rawsyncevent',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sync_source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('mapped_topic_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence_weight', sa.Float(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mapped_topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['sync_source_id'], ['syncsource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rawsyncevent_sync_source_id'), 'rawsyncevent', ['sync_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rawsyncevent_sync_source_id'), table_name='rawsyncevent')
    op.drop_table('rawsyncevent')
    op.drop_table('usermemoryparams')
    op.drop_table('topicprerequisitelink')
    op.drop_index(op.f('ix_syncsource_user_id'), table_name='syncsource')
    op.drop_table('syncsource')
    op.drop_index(op.f('ix_solveattempt_user_id'), table_name='solveattempt')
    op.drop_index(op.f('ix_solveattempt_problem_id'), table_name='solveattempt')
    op.drop_table('solveattempt')
    op.drop_table('problemtopiclink')
    op.drop_index(op.f('ix_learningevent_user_id'), table_name='learningevent')
    op.drop_index(op.f('ix_learningevent_topic_id'), table_name='learningevent')
    op.drop_table('learningevent')
    op.drop_index(op.f('ix_knowledgenode_user_id'), table_name='knowledgenode')
    op.drop_index(op.f('ix_knowledgenode_topic_id'), table_name='knowledgenode')
    op.drop_table('knowledgenode')
    op.drop_index(op.f('ix_calendarconnection_user_id'), table_name='calendarconnection')
    op.drop_table('calendarconnection')
    op.drop_index(op.f('ix_apikey_user_id'), table_name='apikey')
    op.drop_index(op.f('ix_apikey_key'), table_name='apikey')
    op.drop_table('apikey')
    op.drop_index(op.f('ix_agentlog_user_id'), table_name='agentlog')
    op.drop_table('agentlog')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_topic_name'), table_name='topic')
    op.drop_table('topic')
    op.drop_index(op.f('ix_problem_platform_problem_id'), table_name='problem')
    op.drop_index(op.f('ix_problem_platform'), table_name='problem')
    op.drop_table('problem')
    # ### end Alembic commands ###
